import type { Metadata } from "next";
import type { CSSProperties } from "react";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SelectHandler } from "@/components/select-handler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rootStyle = {
  "--font-sans": "ui-sans-serif, system-ui, sans-serif",
} as CSSProperties;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans")} style={rootStyle}>
      <body className="min-h-full flex flex-col">
        <NextTopLoader color="#FFFFFF" showSpinner={false} height={3} />
        <SelectHandler />
        {children}
      </body>
    </html>
  );
}
