FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY --from=builder /app/dist ./dist
COPY src/requests/fonts ./src/requests/fonts
COPY src/requests/assets ./src/requests/assets
EXPOSE 4000
CMD ["node", "dist/main"]
